attach(Train)
sample1 <-sample(10999,500,replace=FALSE)
df1 <- data.frame(Train$ï..ID[sample1],Train$Warehouse_block[sample1],Train$Mode_of_Shipment[sample1],Train$Customer_care_calls[sample1],Train$Customer_rating[sample1],Train$Cost_of_the_Product[sample1],Train$Prior_purchases[sample1],Train$Product_importance[sample1],Train$Gender[sample1])
hist(df1$Train.Customer_rating.sample1.)
hist(df1$Train.Cost_of_the_Product.sample1.)
hist(Train$Cost_of_the_Product)
hist(df1$Train.Prior_purchases.sample1.)
hist(Train$Prior_purchases)
str(Train$Mode_of_Shipment)
str(Train)
plot(Train$Prior_purchases)
cylinders <- table(Train$Prior_purchases)
barplot(cylinders)
c1 <- table(Train$Customer_rating)
barplot(c1)
c1 <- table(Train$Cost_of_the_Product)
barplot(c1)
a1 <- table(Train$Mode_of_Shipment)
pie(a1)
customerr <- table(Train$Customer_rating)
barplot(customerr)
gen1 <- table(Train$Gender)
pie(gen1)
customer_calls <- table(Train$Customer_care_calls)
barplot(customer_calls)
warehouse <- table(Train$Warehouse_block)
barplot(warehouse)
pimp <- table(Train$Product_importance)
pie(pimp)
days <- table(Train$Reached.on.Time_Y.N)
pie(days)
l1 <- lm(Train$Customer_care_calls~Train$Customer_rating)
plot(Train$Customer_care_calls$fitted.values~Train$Customer_rating)
cor(Train$Discount_offered,Train$Reached.on.Time_Y.N)
plot(Train$Prior_purchases,Train$Customer_rating)
boxplot(Train$Discount_offered~Train$Reached.on.Time_Y.N)
boxplot(Train$Cost_of_the_Product~Train$Reached.on.Time_Y.N)
boxplot(Train$Customer_rating~Train$Reached.on.Time_Y.N)
t1 <- table(Train$Reached.on.Time_Y.N,Train$Gender)
barplot(t1,beside=T)
t2 <- table(Train$Reached.on.Time_Y.N,Train$Mode_of_Shipment)
barplot(t2,beside=T,ylim = c(0,5000))
t3 <- table(Train$Reached.on.Time_Y.N,Train$Product_importance)
barplot(t3,beside=T,ylim = c(0,5000))
t4 <- table(Train$Reached.on.Time_Y.N,Train$Customer_care_calls)
barplot(t4,beside=T,ylim=c(0,4000))        
